global using System;
global using static System.Console;
global using System.Diagnostics;
global using System.Text.Json;
global using System.Collections.Generic;
global using System.Linq;
global using WebWindow.Internal;
global using static WebWindow.Native.Gio;
global using static WebWindow.Native.GObject;
global using static WebWindow.Native.Gtk;
global using static WebWindow.Native.WebKit;
global using static WebWindow.Internal.Utilities;