name: Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    - name: Add GitHub source
      run: dotnet nuget add source https://nuget.pkg.github.com/JinShil/index.json --name JinShil --username JinShil --password ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text
    - name: Add dotnet source
      run: dotnet nuget add source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json --name dotnet7
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet nuget push **/*.nupkg -s JinShil --skip-duplicate
      